
name: Atualizar XP e Nível do Personagem

on:
  push:
    branches: [main]
  schedule:
    - cron: '0 0 * * *'

jobs:
  update-xp:
    runs-on: ubuntu-latest

    steps:
    - name: Clonar repositório
      uses: actions/checkout@v3

    - name: Obter número de commits
      run: |
        XP=$(git rev-list --count HEAD)
        NIVEL=$(( (XP + 999) / 1000 ))
        [ $NIVEL -gt 10 ] && NIVEL=10

        echo "XP=$XP" >> $GITHUB_ENV
        echo "NIVEL=$NIVEL" >> $GITHUB_ENV

    - name: Atualizar README com novo XP
      run: |
        sed -i "s/{{XP}}/$XP/g" README.md
        sed -i "s/{{NIVEL}}/$NIVEL/g" README.md
        sed -i "s|src="./personagem/nivel_.*.svg"|src="./personagem/nivel_${NIVEL}.svg"|g" README.md

    - name: Commitar alterações
      run: |
        git config user.name github-actions
        git config user.email github-actions@github.com
        git commit -am "🏹 Atualizando XP e nível para $NIVEL"
        git push
